[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; PARTISI BESAR (Wajib untuk program besar)
board_build.partitions = huge_app.csv

; LIBRARY SENSOR (Download otomatis)
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit INA219 @ ^1.2.3

; KONFIGURASI MEMORI (PENTING! Jangan dihapus)
build_flags = 
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=65536